//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionInox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bon
    {
        public int idB { get; set; }
        public int NumB { get; set; }
        public Nullable<System.DateTime> dateV { get; set; }
    }
}
