//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionInox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int idS { get; set; }
        public Nullable<int> Nom { get; set; }
        public Nullable<int> Qte { get; set; }
        public Nullable<double> PrixU { get; set; }
        public string TypeA { get; set; }
    
        public virtual Produit Produit { get; set; }
    }
}
