//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionInox
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableClient
    {
        public int idC { get; set; }
        public string Nom { get; set; }
        public string Prénom { get; set; }
        public string Tel { get; set; }
        public string Adresse { get; set; }
    }
}
